package com.agit.crm.shared.type;

/**
 *
 * @author ASUS
 */
public enum RoleGroupType {
    ADMIN,
    USER,
    SERVICE_DESK_LEVEL_1,
    SERVICE_DESK_LEVEL_2,
    SERVICE_DESK_LEVEL_3,
    INCIDENT_MANAGEMENT_LEVEL_1,
    INCIDENT_MANAGEMENT_LEVEL_2,
    INCIDENT_MANAGEMENT_LEVEL_3,
    PROBLEM_MANAGEMENT_LEVEL_1,
    PROBLEM_MANAGEMENT_LEVEL_2,
    PROBLEM_MANAGEMENT_LEVEL_3,
    REQUEST_FULLFILMENT_LEVEL_1,
    REQUEST_FULLFILMENT_LEVEL_2,
    REQUEST_FULLFILMENT_LEVEL_3
}
